### ISSUE TITLE
mina-loader@^1.7.0 not including subpackageMapping (https://github.com/tinajs/mina-webpack/pull/111/files) changes

### ISSUE THREAD

**Issue by MingruiZhang** [tinajs/mina-webpack#117]
When upgrading 
```
@tinajs/mina-entry-webpack-plugin": "^1.4.0",
@tinajs/mina-loader": "^1.7.0
"@tinajs/mina-runtime-webpack-plugin": "^1.3.1
```
to include changes of 
https://github.com/tinajs/mina-webpack/pull/111/files, I'm getting error that 
![image](https://user-images.githubusercontent.com/5669963/65825599-7c0ca800-e2ab-11e9-9e66-8f1aa1c15f7b.png)

Seems to me like `mina-entry-webpack-plugin` is working because it moved the icon folders to subPackage, however, mina-loader did not work because it didn't resolve the new path correctly.

I looked into the the node_modules, seems like `@tinajs/mina-loader": "^1.7.0` does not include changes from the https://github.com/tinajs/mina-webpack/pull/111/file , I searched for `subpackageMapping` inside `lib/loaders/mina-json.js`. But it doesn't exist.

Repro steps: 
1. Visit npm registry https://registry.npmjs.org/@tinajs/mina-loader/-/mina-loader-1.7.0.tgz#b7771063a053ffe7112fbf3f3fe9da1da4f948e6
2. open `lib/loaders/mina-json.js`
3. search for keyword `subpackageMapping`, **does not exist**

In compare
1. Visit https://registry.npmjs.org/@tinajs/mina-entry-webpack-plugin/-/mina-entry-webpack-plugin-1.4.0.tgz#e8b37b3fc20a6177d21fa84aa87c41c373ec4922
2. open `lib/index.js`
3. search for keyword `subpackageMapping`, **does exist**

cc @malash @imyelo

**Comment by imyelo** [comment]
Thanks for the feedback!
Found out the build script for mina-loader was missing. Has been added back and republished now.
