### ISSUE TITLE
不使用单文件形式的页面wxss文件使用postcss语法会报解析错误，是postcss-loader没有生效么？

### ISSUE THREAD

**Issue by peirancao** [tinajs/mina-webpack#150]
通过 sao mina my-app创建的项目

**Comment by imyelo** [comment]
https://github.com/tinajs/template-mina/blob/25450d5/template/webpack.config.js

应该是支持的，具体的异常日志和文件内容是?

**Comment by peirancao** [comment]
![image](https://user-images.githubusercontent.com/2832545/86190677-9267cd00-bb77-11ea-9eff-3556f105232b.png)

**Comment by imyelo** [comment]
文件分离型的组件属于兼容处理，保持和微信官方一致的设定，所以不支持 loader。
