### ISSUE TITLE
建议config的默认配置

### ISSUE THREAD

**Issue by Alphmega** [tinajs/mina-webpack#27]
建议在没有config标签的情况也生成json文件，并且将```{ component: true, usingComponents: {}}```作为默认值（除了app.mina外）
这样有一个好处，组件不需要额外设置`component: true`， 而这个设置不会对page产生任何影响，设置```usingComponents: {}```，可以用Component来为page的初始化，而不需要设置额外的config，且不会对component产生任何影响

**Comment by imyelo** [comment]
默认给 Page 也填入 `component: true` 不太合适。虽然现在小程序不太严谨，不会产生负面影响，但和参数本身的意义相悖，容易令人困惑；另一方面会留下隐患，以后小程序对这个参数做严格检查也是有可能的。

满足同样的场景，可能为编辑器做一些自动生成代码块的能力会更适合？

**Comment by Alphmega** [comment]
你说的合理，按照tx的尿性，留下隐患是有可能的。但官方文档上已经说明page本身是component，除非他自己打自己脸。另外如果我想达到这样的效果，可能有方案提供与否？
