### ISSUE TITLE
wxs路径生成有误

### ISSUE THREAD

**Issue by Alphmega** [tinajs/mina-webpack#28]
嵌套复杂的pages文件夹里边的mina文件中引用wxs，最终生成的wxs引用目录不对，比如在 'pages/a/b/c.mina' 引用 '../../../wxs/s.wxs'，最终在pages/a/b/c.wxml里边的路径是 '../wxs/s.xxxx.wxs' 这明显不正确

**Comment by Alphmega** [comment]
我是直接根据这个registry的example上改的

**Comment by imyelo** [comment]
加上去正常了吗？

**Comment by Alphmega** [comment]
example上已经有这条规则，只需要在example/src/pages里边随意建一个文件夹再随意建一个mina文件，引用一个../../wxs/now.wxs，生成出来的路径还是不对的，100%生效

**Comment by imyelo** [comment]
🤔 我刚还试了次是正常的

```xml
<!-- pages/a/b/message.wxml -->
<view>
  <view>Roll: {{ random }}</view>
  <view>Now: {{ now }}</view>

  <wxs module="random">
    var MAX = 100
    module.exports = Math.floor(Math.random() * MAX)
  </wxs>
  <wxs src="../../../wxs/now.d48d5d.wxs" module="now" />
</view>
```

**Comment by Alphmega** [comment]
我刚还测试了次是不正常的，windows 10上测试的，一切如常的安装依赖，就是生成出来的不对 😭

**Comment by imyelo** [comment]
唔 我晚些用 windows 试试能不能重现

**Comment by Alphmega** [comment]
起码你是没问题的，就证明应该不是大问题了，拜托了，我项目在用，看好这个项目，修好publish一下 😭

**Comment by Alphmega** [comment]
刚发现了，如果只有单个wxs引用的时候是没有问题的，多个不同路径深度引用的情况，就会出错，这个应该跟平台没关系

**Comment by imyelo** [comment]
谢谢支持~ 😄
 
方便把重现的文件内容发一下吗？

**Comment by Alphmega** [comment]
我找到了原因，并且尝试修复了
***mina-loader/lib/loaders/mina.js*** 在调用wxml-loader的时候需要传递root和enforceRelativePath这两个参数
```
const LOADERS = {
  template: ({ publicPath, root }) =>
    `${resolve('wxml-loader')}?${JSON.stringify({ publicPath, enforceRelativePath: true, root })}`, // 修改的代码
  style: ({ publicPath }) =>
    `${resolve('extract-loader')}?${JSON.stringify({ publicPath })}!${resolve(
      'css-loader'
    )}`,
  script: () => '',
  config: ({ publicPath }) =>
    `${minaJSONFileLoaderPath}?${JSON.stringify({ publicPath })}`,
}
```
```
  const options = merge(
    {},
    {
      loaders: {},
      languages: {},
      publicPath: this.options.output.publicPath,
      root: this.options.context // 新增的代码
    },
    loaderUtils.getOptions(this) || {}
  )

```

example里边的webpack.config不再需要relative-file-loader 而是改用file-loader

**Comment by imyelo** [comment]
@Alphmega 你的 node 和 npm 的版本是？

**Comment by Alphmega** [comment]
npm -v
5.6.0
node -v
v8.11.3

**Comment by imyelo** [comment]
我换了 win10 和 ubuntu 18.04，也尝试了这样不同路径深度的引用：

```xml
<template>
  <view>
    <view>Roll: {{ random }}</view>
    <view>Now: {{ now }}</view>

    <wxs module="random">
      var MAX = 100
      module.exports = Math.floor(Math.random() * MAX)
    </wxs>
    <wxs src="../nearby/foo.wxs" module="foo" />
    <wxs src="../../../wxs/now.wxs" module="now" />
    <wxs src="../../../wxs/submodule/bar.wxs" module="bar" />
  </view>
</template>

<script>
Page({})
</script>
```

但都没能重现这个问题。方便发下你的 `.mina`, `.wxs` 以及 `webpack.config.babel.js` 文件吗？

**Comment by Alphmega** [comment]
单个文件引用不同深度的wxs应该不会错，是**多个文件**引用**不同深度**的**同一个wxs**才能重现，我用的例子就是example多加了一个不同深度引用now.wsx的page的例子而已

**Comment by imyelo** [comment]
@Alphmega 确认了可以重现。

相关 issues：
- https://github.com/webpack-contrib/file-loader/issues/221
- https://github.com/webpack-contrib/file-loader/issues/149

**Comment by Alphmega** [comment]
实际上这个issue的楼主就是wxml-loader的作者，他应该已经在wxml-loader给出了解决方案，上面我给出的解决方案，其实是通过debug wxml-loader得出的结果，wxml-loader的文档我没细看，不知道是否正确并且达到效果

**Comment by imyelo** [comment]
@Alphmega 是的这个方案可以。来个 PR 吗？或者我晚些处理也行。
