### ISSUE TITLE
默认无法使用 @import

### ISSUE THREAD

**Issue by ambar** [tinajs/mina-webpack#3]
```css
<style>
@import './styles/utils.wxss';
</style>
```

配置一个 `postcss-import` 可以工作，但行为会不一样，它会内联样式。

**Comment by imyelo** [comment]
在 ``<style>`` 里用 ``import`` 得另外配置一条 webpack loader 解析对应的文件名 (比如 ``*.wxss``、``*.css``)

具体：
https://github.com/tinajs/mina-webpack/commit/2958d6eae421a0879f4b1038357710a870917797

另外，默认的项目模板没有这条配置会造成困惑吗，你的看法是？

**Comment by ambar** [comment]
会有困惑，因为缺省配置时没有和原生的开发方式一样工作。
看起来是 css-loader 处理了 `@import` 调用，不确定可不可以让它不去识别。

**Comment by imyelo** [comment]
确实是 css-loader 的原因。

https://github.com/tinajs/mina-webpack/blob/2958d6eae421a0879f4b1038357710a870917797/packages/mina-loader/lib/loaders/mina.js#L16-21

可以考虑给个 option 覆盖这里默认的 ``LOADERS``

**Comment by imyelo** [comment]
目前先在默认项目模板里加了样式 loader 的配置：

https://github.com/tinajs/template-mina/tree/0.1.8

如果还有问题请随意 reopen 😉

**Comment by ambar** [comment]
@imyelo 昨天尝试创建了一个脚手架（[new-mina](https://github.com/ambar/new-mina)），与 template-mina 稍微不同：

- 用 CRA 的方式简化项目创建，隐藏 webpack 配置
- 增加开发工具配置 `project.config.json`
- 用 `prettier.config.js` 控制 code style
- 增加 `.gitattributes`（高亮代码），方便 code review
- 增加 `.vscode`，关联 `.mina` 为 `.vue`
- 配置 `postcss-import`（我们习惯用 postcss-cssnext）

**Comment by imyelo** [comment]
@ambar :+1: 棒～ 介意我把里面的几个 features 同步到 template-mina 里吗？

**Comment by ambar** [comment]
@imyelo 欢迎！

**Comment by imyelo** [comment]
@ambar 

用 postcss-import 处理 ``@import``，相比 [添加 webpack loader 规则](https://github.com/tinajs/template-mina/commit/825e13d56681bac4cc95d63e9f947d1749cb4a40) 有什么优势吗？

考虑到用户可能更习惯于用其他预处理器（比如 less、sass），我更倾向通过 webpack 的配置直接支持这个特性。

**Comment by ambar** [comment]
@imyelo 只是做出了不同的缺省偏好吧:
- template-mina：偏好 precss（sass 式），可以更换插件
- [new-mina/.../postcss.config.js](https://github.com/ambar/new-mina/blob/master/packages/mina-scripts/templates/js/postcss.config.js)：只修复 `@import`，其他仍然是纯 CSS，可以补充插件，例如增加 `require('postcss-cssnext')` —— 这是我们的偏好。

precss 内部是实际是使用了 postcss-import 的:

```
└─┬ precss@2.0.0
  └─┬ postcss-partial-import@4.1.0
    └── postcss-import@10.0.0 
```

暴露出 postcss.config.js，但不做太多选择我感觉可能更好。

（如果不使用 postcss，可以禁用 css-loader 的 `import` 选项，但又要考虑被 import 的文件的复制文件，变得不方便）

**Comment by imyelo** [comment]
嗯，偏好，甚至 template-mina 里 precss 也是可以去掉的，。

**Comment by imyelo** [comment]
嗯，确实是偏好不同，甚至 template-mina 里的 precss 也可以去掉，而 CRA 的方式可以默认写入更多推荐的配置。
