### ISSUE TITLE
mina-loader是否可以适用类似vue-loader 15以上的策略来进行优化

### ISSUE THREAD

**Issue by harvey-woo** [tinajs/mina-webpack#31]
比如熟知的情况，在wxss里边引入的背景图是不能使用本地路径的，所以如果需求是经过wxss上的图片都使用base64-inline-loader来处理，而不是file-loader，以现在的情况，是否有方案可以区分是经过mina-loader后引用的wxss里边的图片
如果是vue-loader v15的话，可以通过issuer来区分

**Comment by imyelo** [comment]
1. 在 wxss 里以 inline 的方式引用图片：

    目前推荐借助 postcss 的 [postcss-url](https://github.com/postcss/postcss-url/) 插件实现：

    https://github.com/tinajs/template-mina/blob/5a185b2516342cb716a36e84ca0cc5dad70c092c/template/postcss.config.js

    ```javascript
    // postcss.config.js
    module.exports = {
      // ...
      plugins: [
        // ...
        require('postcss-url')({ url: 'inline' }),
        // ...
      ],
    }
    ```

    如果不喜欢用 postcss，备选方案是通过在 webpack 配置中约定路径规则从而区分图片资源是用于 wxss 还是 wxml / js：

    ```javascript
    // webpack.config.babel.js
    // module.rules:
    // ...
          {
            test: /\.(png|jpg|jpeg|gif|svg)$/,
            include: path.resolve(__dirname, 'src/assets/copy'),
            use: {
              loader: 'file-loader',
              options: {
                name: 'assets/[name].[hash:6].[ext]',
              },
            },
          },
          {
            test: /\.(png|jpg|jpeg|gif|svg)$/,
            include: path.resolve(__dirname, 'src/assets/inline'),
            use: {
              loader: 'url-loader',
            },
          },
    // ...
    ```

2. Loader 推导确实是个很优雅的设计，但需要额外引入 plugin，与 loader 的耦合会变得更重；其次也不能直接解决前面的第一个问题，所以暂时不计划采用。

相关讨论:
- https://github.com/tinajs/mina-webpack/pull/22#issuecomment-412332473

**Comment by Alphmega** [comment]
仔细想想你提供的方案还是不够优雅
1. 首先我不希望引入postcss，还是希望在webpack的流程上处理
2. 方案二的前提是图片目录划分得足够细致的情况下，但实际情况有些图片既用在wxss上，也用在wxml上，一竹竿根据路径还是不合理

现在我的方案是通过resourceQuery去判断，?inline的图片则通过base64，但是这样设置还是比较繁琐，需要按需每个图片加入inline

我希望开发人员实际上是不需要关注整个构建过程，就能很愉快的在不同场景使用图片，而不会导致任何问题。实际上在production情况下，我还会把图片上传，并且替换部分路径。所以其实我之前说的 inline的需求，其实是个**伪需求**，在我开发过程只是为了解决**小程序在css不支持图片的问题，而已**，我不希望因为这个伪需求，而让其他开发者去划分文件目录，或者刻意增加inline

大神，你能为我这个场景提供更好的方案么？

感谢阅读

**Comment by imyelo** [comment]
嗯，一但接受 wxss 中不支持 `url()` 使用相对路径的设定，这个问题就确实应该在 loader 内部被消化掉。

大致想了下，有以下两个途径可以支持这个设定：

1. 在 [mina-loader 内置的 css-loader](https://github.com/tinajs/mina-webpack/blob/28779c/packages/mina-loader/lib/constants.js#L31) 中将 [`url` 参数](https://github.com/webpack-contrib/css-loader#url) 设为 `false`，以阻止它处理 `url()`，并在其后方额外内置一个新的 loader (比如 wxss-loader、postcss-url-loader、或者其他名字)，在内部使用 postcss 和 postcss-url 处理 wxss 中的 `url()`。

    对于 PostCSS 用户而言，postcss-url 是个很好的插件 —— 除了可以把图片转为 base64 (inline) 以外，也可以满足正式包中 [生成 CDN 路径](https://github.com/postcss/postcss-url#muiltiple-options) 的场景。

    所以这个额外的 loader 还可以接受 [与 postcss-url 一致的 `url` 参数](https://github.com/postcss/postcss-url#url)，从而满足本地包内联 base64 / 正式包替换为 CDN 路径的需求。

2. 直接废弃 mina-loader 内置的 css-loader，替换为 fork 的新 loader，并实现上一个方式的 features。

**Comment by imyelo** [comment]
从刚发布的 [mina-loader@1.1.0](https://github.com/tinajs/mina-webpack/tree/%40tinajs/mina-loader%401.1.0) 开始，`style` 区块内的 `url` 默认将被转为行内地址 (`base64`)。即在内部消化掉这个问题，无需再额外使用 PostCSS 或其他预编译器处理。

另外，如果需要更自由地操作 `url` —— 例如拷贝图片文件到指定目录并将请求重命名为 CDN 上的远程地址，则推荐通过额外使用 PostCSS + `postcss-url` 实现，示例：

- https://github.com/tinajs/mina-webpack/blob/f88a902024/packages/mina-loader/test/wxss.js#L41-L69
- https://github.com/tinajs/mina-webpack/blob/f88a902024/packages/mina-loader/test/fixtures/wxss/postcss.config.js

**Comment by imyelo** [comment]
issue 暂时先关闭了，如果还有问题请随意 reopen 😉
