### ISSUE TITLE
在引入错误的包的时候`npm start`直接退出

### ISSUE THREAD

**Issue by run27017** [tinajs/mina-webpack#44]
在.mina文件的config内部如果引入错误的文件，编译环境直接退出了：

```json5
{
  "usingComponents": {
    "van-nav-bar": "~vant-weapp/dist/nav-bar/index",
    // 直接npm start退出
    "van-action-sheet": "~vant-weapp/dist/actionsheet/index"
  }
}
```

退出报错：

> Error: Cannot find module 'vant-weapp/dist/actionsheet/index'

这样可能不太好，可以考虑捕获这个异常，然后打印出错误就好了。不要让整个开发环境退出。

**Comment by imyelo** [comment]
Close with https://github.com/tinajs/mina-webpack/pull/48
