### ISSUE TITLE
add a way to customize toSafeOutputPath logic

### ISSUE THREAD

**Issue by Jimexist** [tinajs/mina-webpack#45]
for now the logic of `toSafeOutputPath` is to escape using `_` and also special handling for `node_modules`. However I think there should be more customizable way to handle this.

https://github.com/tinajs/mina-webpack/blob/96377e5e756a7bc27b8b8bb5debf011fb6c49ae2/packages/mina-entry-webpack-plugin/lib/helpers/index.js#L1

**Comment by Jimexist** [comment]
i've got the `.js` files correctly put into `_node_modules_` file however the other three (`.json`, `.wxml`, and `.wxss`) still not changed

**Comment by imyelo** [comment]
> i've got the .js files correctly put into _node_modules_ dir however the other three (.json, .wxml, and .wxss) still not changed

This problem should be fixed in https://github.com/tinajs/mina-webpack/commit/096d2dba4e3830ff52d35ad2de3508679f5b8d7f (v1.0.0-8) 😉
