### ISSUE TITLE
是否有可能自定义编译文件名

### ISSUE THREAD

**Issue by baranwang** [tinajs/mina-webpack#59]
因为看目前的各家小程序的结构基本都是一致的，除了文件名和一些 API 前缀不同。所以是否有可能在项目中配置文件名后缀来进行编译呢？
（不太赞同一次编译自动转换的方式，毕竟有些地方还是有差异化的）

**Comment by imyelo** [comment]
是指在项目中同时编写各端专用的文件，例如 `page.mina`、`page.ant.mina`、`page.swan.mina`，然后根据目标平台编译对应文件吗

**Comment by baranwang** [comment]
这种就类似 react 咯，我本身的意思是比较简单化的。
比如在根目录有个配置文件，可以定义输出的 html 的后缀为 wxml / axml / swan 等

**Comment by imyelo** [comment]
最近刚好给 mina-loader 加了一个参数 `extensions`，可以设置输出文件的后缀名：

https://github.com/tinajs/mina-webpack/tree/7cece04/packages/mina-loader#options

**Comment by baranwang** [comment]
👍期待 release

**Comment by imyelo** [comment]
嗯，^1.4 已经包含这个选项。
