### ISSUE TITLE
全新安装无法引用 npm 上的 mina 包

### ISSUE THREAD

**Issue by ambar** [tinajs/mina-webpack#6]
重现：删掉 example 下的 package-lock.json，运行 npm install，或直接运行 yarn。

注意到的一点区别是，全新安装 css-loader 是 `0.28.10`，如果降级它为 `0.28.9` 或以下能工作，但没看出这个改动有什么不对：https://github.com/webpack-contrib/css-loader/compare/v0.28.9...v0.28.10

不太肯定是不是 css-loader 问题🤔

**Comment by imyelo** [comment]
对比了下 package-lock.json

```diff

    "@tinajs/mina-loader": {
      "version": "0.5.1",
      "resolved": "http://registry.npm.taobao.org/@tinajs/mina-loader/download/@tinajs/mina-loader-0.5.1.tgz",
      "integrity": "sha1-6N9cwwp25mvfo+lHkMK+MIlCeIk=",
      "dev": true,
      "requires": {
        "@tinajs/mina-sfc": "0.2.1",
        "compose-function": "3.0.3",
        "css-loader": "0.28.10",
        "ensure-posix-path": "1.0.2",
        "extract-loader": "1.0.2",
        "file-loader": "1.1.11",
        "json5": "0.5.1",
        "loader-utils": "1.1.0",
        "lodash.merge": "4.6.1",
        "object-path": "0.11.4",
        "p-all": "1.0.0",
        "p-map": "1.2.0",
        "replace-ext": "1.0.0",
        "style-loader": "0.19.1",
        "vue-template-compiler": "2.5.13",
        "wxml-loader": "0.1.2"
      }
```

排查下来应该是 extract-loader 和 css-loader 一起升级后触发的问题

https://github.com/peerigon/extract-loader/pull/30
https://github.com/peerigon/extract-loader/issues/29

**Comment by imyelo** [comment]
发了个 mina-loader 的版本 [(0.5.2)](https://github.com/tinajs/mina-webpack/releases/tag/%40tinajs%2Fmina-loader%400.5.2)，在 https://github.com/peerigon/extract-loader/pull/30 被合并之前，暂时将 extract-loader 的版本固定在 1.0.1 了。

@ambar 方便确认下是否解决了问题吗？

**Comment by ambar** [comment]
解决了 👍
