### ISSUE TITLE
无法设置 enforceRelativePath，因为在默认 loaders 中写死了

### ISSUE THREAD

**Issue by mrbone** [tinajs/mina-webpack#72]
`packages/mina-loader/src/constants.ts:L21-36`

```ts
template: ({
    publicPath,
    context,
    minimize,
  }: {
    publicPath: string
    context: any
    minimize: boolean
  }) =>
    `${resolve('@tinajs/wxml-loader')}?${JSON.stringify({
      publicPath,
      enforceRelativePath: true,
      root: context,
      minimize,
      raw: true,
    })}`,
```
造成的问题是哪怕我在 `mina-loader` 中配置 

```js
template:{
  loader: '@tinajs/wxml-loader',
  options: {
    enforceRelativePath: false
  }
}
```
也会被默认的覆盖掉，这里建议 merge 下 options 吧。

**Comment by imyelo** [comment]
设置 false 会影响 wxs 文件生成，所以作为内置配置写死了，相关问题 #28 。

你需要用绝对路径的场景是？

**Comment by mrbone** [comment]
我有一个图片组件需要用到绝对路径从跟节点引用图片。图片的 src 基于手机分辨率是动态生成的。

组件在 
components/base/my-image.mina

图片在
images/a.png

pages/A.mina 中
```vue
<template>
  <my-image src="/images/a.png">
</template>
```

转换出来的 wxml 是

```
<template>
  <my-image src="../images/a.png">
</template>
```
因为在 my-image 中原本是通过根目录 images 拿到图片的，现在是相对路径，并且层级是父组件的路径，所以出现图片拿不到。
这个组件的实现个人感觉是有点问题，但是现在这样在 template 里面也没法使用绝对路径了。

**Comment by imyelo** [comment]
如果不想被 loader 改变路径的话，可以：

```html
<template>
  <my-image src="{{ '/images/a.png' }}">
</template>
```

不过这样的话图片也不会被复制到 `dist` 里,这种写法更适合用在已经上传至线上的图片。

或者试试给根目录设置一个 alias 呢？例如：

```javascript
// webpack.config.js
// ...
  resolve: {
    alias: {
      '$': resolve('src'),
    },
  },
// ...
```

```html
<template>
  <my-image src="$/images/a.png">
</template>
```

**Comment by mrbone** [comment]
如何实现那个功能都不是什么大问题，大不了不用 src做属性也能实现，我的困惑是强制模板只能用相对路径这种实现貌似不太合理，毕竟wxml-loader是有这个接口的个人认为是可以默认为相对路径，用户可以自己去复写 loader 配置项更合理一些。

**Comment by imyelo** [comment]
[@tinajs/mina-loader@1.5.1](https://github.com/tinajs/mina-webpack/releases/tag/%40tinajs%2Fmina-loader%401.5.1) released
