### ISSUE TITLE
不能引用 npm 的 pages

### ISSUE THREAD

**Issue by mrbone** [tinajs/mina-webpack#74]
`loaders/mina-json` 会把 `config` 中的 npm 模块通过 `toSafeOutputPath` 放到 `dist/_/_` 目录中，这在复用 components 是工作的，因为小程序没有限制组件的路径。但是 pages 不行，目前 pages 只能放到 pages 的一级目录下面。

这里能不能加个判断，如果有 pages 目录则放到 dist 的一级目录(虽然有覆盖的风险，有时间的话可以加个覆盖提示)。类似:

```js
exports.toSafeOutputPath = function(original) {
  return original.indexOf(/\/pages\//) === -1 
 ? (original || '')
    .replace(/\.\./g, '_')
    .replace(/node_modules([\/\\])/g, '_node_modules_$1')
 : `pages/${origin.replaced}`
}
```

**Comment by imyelo** [comment]
试了下，pages 没有这个限制，是不是有别的问题？

截图：
![screenshot](https://i.loli.net/2019/05/11/5cd6dc4350ac6.png)

**Comment by mrbone** [comment]
试了下，应该是我没有更改编译的 url 的原因。。。

**Comment by imyelo** [comment]
:smile: redirectTo 的时候直接用了 node_modules 的地址么？这点确实会让人困惑

**Comment by mrbone** [comment]
> 😄 redirectTo 的时候直接用了 node_modules 的地址么？这点确实会让人困惑

我没有在编译模式下更新成编译后的 url: `_/_/common/pages/somePage/index`。 :(
