### ISSUE TITLE
无法引用 wxs 的问题

### ISSUE THREAD

**Issue by ambar** [tinajs/mina-webpack#9]
- 一种可能性是像 `<image src />` 一样被微信官方支持：[wxs 无法以绝对路径引用 
](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0006661d1808c0e5f2665c9c95b400)
- 或者升级 `wxml-loader`，再配置 `enforceRelativePath` 和 `root` 参数的同时，设定 `file-loader` 的 `useRelativePath` 和 `context` 参数 —— 四个参数设置有点麻烦
- 或者 fork `file-loader`，像这样改动： [relative-file-loader/src/index.js#L47-L50](https://github.com/ambar/relative-file-loader/blob/7f1222d4f885cc1efee4583ef6d8b19d87c34591/src/index.js#L47-L50) ，调整生成 public path 的方式，确保只生成相对路径

**Comment by imyelo** [comment]
wxs 目前主要的运用场景应该都是做计算属性，简化 wxml 模板。但因为 [wxs 的 runtime 相对特殊](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxs/#注意)，开发体验糟糕，所以我推荐使用 [tina.js 中的 compute 方法](https://tina.js.org/#/guide/page?id=%e8%ae%a1%e7%ae%97%e5%b1%9e%e6%80%a7) 代替，并避免使用 wxs。

如果无法避免，比如在旧项目中已经使用了 wxs，或者希望借助 wxs 做性能优化，那么推荐通过以下两种方式使用：

1. 在 ``<template>`` 中直接内联 ``<wxs>`` 的内容：

```html
<!-- page.mina -->
<template>
  <view>
    <view>Roll: {{ random }}</view>
    <wxs module="random">
      var MAX = 100
      module.exports = Math.floor(Math.random() * MAX)
    </wxs>
  </view>
</template>

<script>
Page({})
</script>
```

2. 与 @ambar 的思路一致，引入 ``relative-file-loader`` [(示例)](https://github.com/tinajs/mina-webpack/commit/061639e1faae7a0381ce698bbb4c5e29b89d7d14)：

```js
// webpack.config.js
// ...
      {
        test: /\.wxs$/,
        use: {
          loader: 'relative-file-loader',
          options: {
            name: 'wxs/[name].[hash:6].[ext]',
          },
        },
      },
// ...
```

```html
<!-- page.mina -->
<template>
  <view>
    <view>Now: {{ now }}</view>
    <wxs src="../wxs/now.wxs" module="now" />
  </view>
</template>

<script>
Page({})
</script>
```

> 目前微信小程序的 wxml 语法中，暂不支持使用绝对路径引用 wxs 文件。

仍需注意的是，由于 wxs runtime 特殊，所以还无法和普通的 javascript 文件一样直接使用其他 loader 做预编译（例如 babel-loader）。

**Comment by ambar** [comment]
@imyelo 如果是列表中的数组怎么处理呢？

**Comment by imyelo** [comment]
@ambar 

如果用 tina 的 compute：

```javascript
import { Page } from '@tinajs/tina'
import fecha from 'fecha'

Page.define({
  data: {
    messages: [{
      content: 'foobar',
      createdAt: Date.now(),
    }]
  },
  compute ({ messages }) {
    return {
      messages: messages.map((message) => {
        return {
          ...message,
          prettyCreatedAt: fecha.format(message.createdAt, 'YYYY-MM-DD HH:mm:ss'),
        }
      }),
    }
  }
})
```

不过像上面这种场景，确实更适合用 [filter](https://cn.vuejs.org/v2/guide/filters.html) (wxs)。
